apiVersion: v1
kind: Secret
metadata:
  name: session-service-secrets
  namespace: nomnom-system
type: Opaque
stringData:
  # Session service environment variables
  PORT: "5007"
  NODE_ENV: "production"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  SESSION_SECRET: "your-session-secret-here"
  MONGODB_URI: "mongodb+srv://username:password@your-atlas-cluster.mongodb.net/session-service?retryWrites=true&w=majority"
  # Add other required environment variables for session service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: nomnom-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
      - name: session-service
        image: dasunwickr/session-service:latest
        ports:
        - containerPort: 5007
        envFrom:
        - secretRef:
            name: session-service-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: nomnom-system
spec:
  selector:
    app: session-service
  ports:
  - port: 5007
    targetPort: 5007
  type: ClusterIP