apiVersion: v1
kind: Secret
metadata:
  name: delivery-service-secrets
  namespace: nomnom-system
type: Opaque
stringData:
  PORT: "5011"
  NODE_ENV: "production"
  MONGODB_URI: "mongodb+srv://username:password@your-atlas-cluster.mongodb.net/delivery-service?retryWrites=true&w=majority"
  # Add other required environment variables for delivery service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  namespace: nomnom-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
      - name: delivery-service
        image: localhost:5000/delivery-service:latest
        ports:
        - containerPort: 5011
        envFrom:
        - secretRef:
            name: delivery-service-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: nomnom-system
spec:
  selector:
    app: delivery-service
  ports:
  - port: 5011
    targetPort: 5011
  type: ClusterIP